function generatorM(){
    let name1 = ["Aabeli", "Aabi", "Aabrahami", "Aahas", "Aalikki", "Aamen", "Aamunvalo", "Aaprahami", "Aapru", "Aarikki", "Aarmo", "Aarnetti",
    "Aarnoltti", "Aarres", "Aarretti", "Aarro", "Aarti", "Aartsi", "Aarttu", "Aateli", "Aato", "Aatolvi", "Aatsa", "Aatso", "Aatte", "Aattu",
    "Aaveli", "Aavo", "Abrami", "Adonis", "Aetius", "Afrika", "Ahas", "Ahde", "Ahma", "Ahmo", "Ahtu", "Ahve", "Aihe", "Aikamies", "Aikio", "Aikko",
    "Ailu", "Aimone", "Ainar", "Ainu", "Airamo", "Airik", "Airikka", "Airo", "Aivo", "Ajax", "Akatius", "Akke", "Akki", "Akse", "Alaattin", "Alanen",
    "Alari", "Alas", "Albertto", "Alemu", "Alermi", "Alessi", "Alexsanderi", "Alister", "Alkio", "Alkki", "Allah", "Alle", "Allo", "Almar", "Almer",
    "Almi", "Almus", "Alonso", "Alvaro", "Alve", "Amadeo", "Anakin", "Anatolius", "Andreevits", "Anse", "Anselmo", "Ansi", "Antte", "Aaprahami", "Aprami",
    "Arssi", "Artturo", "Arvidi", "Arviidi", "Arviitti", "Askur", "Askuri", "Aslo", "Assari", "Ater", "Atta", "Atti", "Atto", "Attu", "Autere", "Ax",
    "Babar", "Bani", "Beni", "Benedikt", "Black", "Borg", "Chip", "Cicero", "Cosmo", "Dino", "Dublin", "Ee", "Eepo", "Eerikka", "Ekke", "Ekko", "Ekku",
    "Elbertti", "Ele", "Eleasar", "Elio", "Elmari", "Enno", "Ennu", "Enska", "Enso", "Enti", "Erasmus", "Era", "Ertti", "Ertto", "Erve", "Ervi", "Esse",
    "Feeli", "Ford", "Fredrikki", "Freetrikki", "Gigi", "Gil", "Golf", "Halo", "Halvar", "Hami", "Halmet", "Hannibal", "Hansi", "Hartti", "Hassel",
    "Heikka", "Heikkijaakko", "Heka", "Hemi", "Hemo", "Hentrik", "Hentrikki", "Herkules", "Hermes", "Herne", "Hese", "Hilari", "Hillari", "Hilmo",
    "Hirvo", "Hole", "Homo", "Huoti", "Huvi", "Ii", "Iippo", "Iisku", "Ilias", "Ilves", "Im", "Ima", "Immu", "Inko", "Iska", "Ismari", "Ispo", "Itu",
    "Jaakop", "Jaapo", "Jaarli", "Jahvet", "Jaki", "Jame", "Janke", "Janko", "Jante", "Janus", "Jasa", "Jaspar", "Jedi", "Jeemi", "Jehki", "Jemi",
    "Jerkka", "Jermo", "Jimmi", "Jirik", "Joa", "Johani", "Jormo", "Jouhki", "Joulu", "Joutsi", "Juhi", "Juksu", "Junias", "Junne", "Jupiter", "Jöri",
    "Ka", "Kaa", "Kaapre", "Kaapri", "Kaike", "Kaiko", "Kaiku", "Kaima", "Kake", "Kale", "Kallu", "Karma", "Kaspari", "Kaspian", "Kassius", "Kauppi",
    "Kauppo", "Keemo", "Keke", "Kelvin", "Kem", "Kermit", "Kermo", "Kilu", "Kirka", "Kirmo", "Kiwi", "Klaes", "Klementti", "Kliment", "Knuut", "Knuuti",
    "Knuutti", "Kontio", "Kontro", "Kornelius", "Kosma", "Kostja", "Kouta", "Kuku", "Kössi", "Lalo", "Lalu", "Lamperi", "Lampertti", "Lappi", "Leiffi",
    "Leksa", "Lexa", "Len", "Lennartti", "Lennu", "Leonartti", "Leva", "Leve", "Levo", "Liimo", "Lode", "Makari", "Makko", "Maks", "Maksimilian", "Mane",
    "Mani", "Mano", "Manuele", "Manueli", "Marno", "Marton", "Massi", "Mauritius", "Menno", "Meo", "Meritre", "Miihka", "Miihkali", "Miikkali", "Miikkula",
    "Miio", "Miitra", "Miitre", "Miitro", "Mikali", "Mikka", "Mikkal", "Miklas", "Miklo", "Miklos", "Mikos", "Moon", "Moosa", "Moose", "Morits", "Moriz",
    "Morton", "Mortti", "Musta", "Nadi", "Nakke", "Nandor", "Nathanael", "Ned", "Nemo", "Niikko", "Niilas", "Niilles", "Nikki", "Niky", "Nikko", "Niklaus",
    "Nilas", "Nio", "Nipa", "Noeli", "Nuo", "Nut", "Nuu", "Nuuti", "Obelix", "Obi", "Ohvo", "Okka", "Okke", "Oksu", "Olai", "Olaus", "Oleksei", "Oleksi",
    "Oli", "One", "Ontrei", "Ontro", "Ooke", "Opal", "Optatus", "Ora", "Ore", "Orko", "Orri", "Orvar", "Osa", "Oska", "Oski", "Oso", "Osvi", "Otmar",
    "Otro", "Oulas", "Ouli", "Pate", "Patri", "Patrikki", "Patro", "Patu", "Paulos", "Pauni", "Paunu", "Pave", "Pavo", "Peer", "Peeti", "Peitsa", "Pekki", 
    "Peko", "Pellonpekko", "Pena", "Penhartti", "Penjam", "Penna", "Pera", "Perttyli", "Peteris", "Petka", "Petros", "Peetu", "Pieti", "Poul", "Primo",
    "Prokko", "Rainar", "Raito", "Ralfe", "Ramana", "Ramani", "Ramine", "Rane", "Ransu", "Rasmu", "Ree", "Reetu", "Rego", "Reimar", "Reimer", "Reimo",
    "Reinar", "Reinari", "Reinart", "Reinhart", "Remi", "Remo", "Renni", "Repa", "Repe", "Retu", "Revontuli", "Ri", "Rieti", "Rietrikki", "Rietu",
    "Rihko", "Riiko", "Rike", "Rikhartti", "Rikke", "Ro", "Rollo", "Ronni", "Rono", "Roo", "Ru", "Ruu", "Ruupertti", "Ruurikki", "Saammal", "Sakkeus",
    "Sakris", "Salle", "Sammi", "Sammo", "Sammu", "Samo", "Sante", "Santero", "Saulo", "Savi", "Sees", "Seikko", "Semio", "Senior", "Senori", "Sepe",
    "Sepeteus", "Seppi", "Serko", "Sero", "Si", "Sihvertti", "Siilas", "Siinto", "Silvester", "Simana", "Simojussi", "Simopekka", "Simppa", "Simuna",
    "Sing", "So", "Stanislaus", "Stefanos", "Stepanus", "Su", "Tarkko", "Tauri", "Tauvo", "Terenti", "Teutori", "Tiera", "Tihvo", "Tiikka", "Timitri",
    "Timjam", "Timjami", "Timka", "Timotei", "Toffee", "Tommo", "Ugu", "Uke", "Uki", "Uko", "Ukri", "Uku", "Ulias", "Unne", "Unski", "Uule", "Valentinus",
    "Valko", "Valta", "Valton", "Valtti", "Vangs", "Vante", "Vantte", "Vasilli", "Veeliks", "Well", "White", "Vikki", "Vilkko", "Villehart", "Villi",
    "Vilmari", "Vilmeri", "Vilppo", "Vittorio", "Volte", "Vulle", "Väinämöinen", "Ykä", "Yrmy", "Yö", "Zeus", "Örkki"];

    let name2 = ["Aabeli", "Aabi", "Aabrahami", "Aahas", "Aalikki", "Aamen", "Aamunvalo", "Aaprahami", "Aapru", "Aarikki", "Aarmo", "Aarnetti",
    "Aarnoltti", "Aarres", "Aarretti", "Aarro", "Aarti", "Aartsi", "Aarttu", "Aateli", "Aato", "Aatolvi", "Aatsa", "Aatso", "Aatte", "Aattu",
    "Aaveli", "Aavo", "Abrami", "Adonis", "Aetius", "Afrika", "Ahas", "Ahde", "Ahma", "Ahmo", "Ahtu", "Ahve", "Aihe", "Aikamies", "Aikio", "Aikko",
    "Ailu", "Aimone", "Ainar", "Ainu", "Airamo", "Airik", "Airikka", "Airo", "Aivo", "Ajax", "Akatius", "Akke", "Akki", "Akse", "Alaattin", "Alanen",
    "Alari", "Alas", "Albertto", "Alemu", "Alermi", "Alessi", "Alexsanderi", "Alister", "Alkio", "Alkki", "Allah", "Alle", "Allo", "Almar", "Almer",
    "Almi", "Almus", "Alonso", "Alvaro", "Alve", "Amadeo", "Anakin", "Anatolius", "Andreevits", "Anse", "Anselmo", "Ansi", "Antte", "Aaprahami", "Aprami",
    "Arssi", "Artturo", "Arvidi", "Arviidi", "Arviitti", "Askur", "Askuri", "Aslo", "Assari", "Ater", "Atta", "Atti", "Atto", "Attu", "Autere", "Ax",
    "Babar", "Bani", "Beni", "Benedikt", "Black", "Borg", "Chip", "Cicero", "Cosmo", "Dino", "Dublin", "Ee", "Eepo", "Eerikka", "Ekke", "Ekko", "Ekku",
    "Elbertti", "Ele", "Eleasar", "Elio", "Elmari", "Enno", "Ennu", "Enska", "Enso", "Enti", "Erasmus", "Era", "Ertti", "Ertto", "Erve", "Ervi", "Esse",
    "Feeli", "Ford", "Fredrikki", "Freetrikki", "Gigi", "Gil", "Golf", "Halo", "Halvar", "Hami", "Halmet", "Hannibal", "Hansi", "Hartti", "Hassel",
    "Heikka", "Heikkijaakko", "Heka", "Hemi", "Hemo", "Hentrik", "Hentrikki", "Herkules", "Hermes", "Herne", "Hese", "Hilari", "Hillari", "Hilmo",
    "Hirvo", "Hole", "Homo", "Huoti", "Huvi", "Ii", "Iippo", "Iisku", "Ilias", "Ilves", "Im", "Ima", "Immu", "Inko", "Iska", "Ismari", "Ispo", "Itu",
    "Jaakop", "Jaapo", "Jaarli", "Jahvet", "Jaki", "Jame", "Janke", "Janko", "Jante", "Janus", "Jasa", "Jaspar", "Jedi", "Jeemi", "Jehki", "Jemi",
    "Jerkka", "Jermo", "Jimmi", "Jirik", "Joa", "Johani", "Jormo", "Jouhki", "Joulu", "Joutsi", "Juhi", "Juksu", "Junias", "Junne", "Jupiter", "Jöri",
    "Ka", "Kaa", "Kaapre", "Kaapri", "Kaike", "Kaiko", "Kaiku", "Kaima", "Kake", "Kale", "Kallu", "Karma", "Kaspari", "Kaspian", "Kassius", "Kauppi",
    "Kauppo", "Keemo", "Keke", "Kelvin", "Kem", "Kermit", "Kermo", "Kilu", "Kirka", "Kirmo", "Kiwi", "Klaes", "Klementti", "Kliment", "Knuut", "Knuuti",
    "Knuutti", "Kontio", "Kontro", "Kornelius", "Kosma", "Kostja", "Kouta", "Kuku", "Kössi", "Lalo", "Lalu", "Lamperi", "Lampertti", "Lappi", "Leiffi",
    "Leksa", "Lexa", "Len", "Lennartti", "Lennu", "Leonartti", "Leva", "Leve", "Levo", "Liimo", "Lode", "Makari", "Makko", "Maks", "Maksimilian", "Mane",
    "Mani", "Mano", "Manuele", "Manueli", "Marno", "Marton", "Massi", "Mauritius", "Menno", "Meo", "Meritre", "Miihka", "Miihkali", "Miikkali", "Miikkula",
    "Miio", "Miitra", "Miitre", "Miitro", "Mikali", "Mikka", "Mikkal", "Miklas", "Miklo", "Miklos", "Mikos", "Moon", "Moosa", "Moose", "Morits", "Moriz",
    "Morton", "Mortti", "Musta", "Nadi", "Nakke", "Nandor", "Nathanael", "Ned", "Nemo", "Niikko", "Niilas", "Niilles", "Nikki", "Niky", "Nikko", "Niklaus",
    "Nilas", "Nio", "Nipa", "Noeli", "Nuo", "Nut", "Nuu", "Nuuti", "Obelix", "Obi", "Ohvo", "Okka", "Okke", "Oksu", "Olai", "Olaus", "Oleksei", "Oleksi",
    "Oli", "One", "Ontrei", "Ontro", "Ooke", "Opal", "Optatus", "Ora", "Ore", "Orko", "Orri", "Orvar", "Osa", "Oska", "Oski", "Oso", "Osvi", "Otmar",
    "Otro", "Oulas", "Ouli", "Pate", "Patri", "Patrikki", "Patro", "Patu", "Paulos", "Pauni", "Paunu", "Pave", "Pavo", "Peer", "Peeti", "Peitsa", "Pekki", 
    "Peko", "Pellonpekko", "Pena", "Penhartti", "Penjam", "Penna", "Pera", "Perttyli", "Peteris", "Petka", "Petros", "Peetu", "Pieti", "Poul", "Primo",
    "Prokko", "Rainar", "Raito", "Ralfe", "Ramana", "Ramani", "Ramine", "Rane", "Ransu", "Rasmu", "Ree", "Reetu", "Rego", "Reimar", "Reimer", "Reimo",
    "Reinar", "Reinari", "Reinart", "Reinhart", "Remi", "Remo", "Renni", "Repa", "Repe", "Retu", "Revontuli", "Ri", "Rieti", "Rietrikki", "Rietu",
    "Rihko", "Riiko", "Rike", "Rikhartti", "Rikke", "Ro", "Rollo", "Ronni", "Rono", "Roo", "Ru", "Ruu", "Ruupertti", "Ruurikki", "Saammal", "Sakkeus",
    "Sakris", "Salle", "Sammi", "Sammo", "Sammu", "Samo", "Sante", "Santero", "Saulo", "Savi", "Sees", "Seikko", "Semio", "Senior", "Senori", "Sepe",
    "Sepeteus", "Seppi", "Serko", "Sero", "Si", "Sihvertti", "Siilas", "Siinto", "Silvester", "Simana", "Simojussi", "Simopekka", "Simppa", "Simuna",
    "Sing", "So", "Stanislaus", "Stefanos", "Stepanus", "Su", "Tarkko", "Tauri", "Tauvo", "Terenti", "Teutori", "Tiera", "Tihvo", "Tiikka", "Timitri",
    "Timjam", "Timjami", "Timka", "Timotei", "Toffee", "Tommo", "Ugu", "Uke", "Uki", "Uko", "Ukri", "Uku", "Ulias", "Unne", "Unski", "Uule", "Valentinus",
    "Valko", "Valta", "Valton", "Valtti", "Vangs", "Vante", "Vantte", "Vasilli", "Veeliks", "Well", "White", "Vikki", "Vilkko", "Villehart", "Villi",
    "Vilmari", "Vilmeri", "Vilppo", "Vittorio", "Volte", "Vulle", "Väinämöinen", "Ykä", "Yrmy", "Yö", "Zeus", "Örkki"];

    let randomNameM = name1[Math.floor(Math.random() * name1.length)] + " " + name2[Math.floor(Math.random() * name2.length)];

    alert(randomNameM);
}

function generatorF(){
    let name3 = ["Aadaliina", "Aadolfiina", "Aalia", "Aallokki", "Aallokko", "Aamukaste", "Aamunkoi", "Aamurusko", "Aamutuuli", "Aamutähti", "Aana",
    "Aarikka", "Aarna", "Aarnea", "Aarnevi", "Aasia", "Aaluva", "Adelma", "Adolfia", "Adoniikka", "Adora", "Affi", "Africa", "Afrodite", "Agneetta",
    "Agrippiina", "Agrippina", "Agveliina", "Ahava", "Ahkera", "Ai", "Aijali", "Aijeli", "Aijuliina", "Aika", "Ailama", "Ailamo", "Ailikka", "Ainara",
    "Aine", "Aineli", "Aines", "Ainiina", "Ainikka", "Ainoa", "Ainokainen", "Ainokki", "Ainotar", "Ainut", "Airiina", "Aiselu", "Ajatar", "Akaata",
    "Akasia", "Akileia", "Akileija", "Akiliina", "Akillea", "Akita", "Akka", "Akliina", "Akneetta", "Akraseena", "Akselia", "Akseliina", "Aksella",
    "Aksia", "Aksiina", "Aksinja", "Akta", "Akusta", "Akustiina", "Akveliina", "Akviliina", "Albania", "Aldine", "Aleena", "Aleftiina", "Aleksanna",
    "Aleta", "Aletta", "Alexiina", "Alfiina", "Alfriida", "Algi", "Alilla", "Alita", "Alja", "Alkviliina", "Allas", "Allegra", "Alliida", "Almaz",
    "Almiina", "Alna", "Alsine", "Alvia", "Alvira", "Alviira", "Ameli", "Anjussi", "Anneke", "Anseriina", "Anuska", "Arizona", "Arnikki", "Asia",
    "Aspasia", "Atsalea", "Auguste", "Auna", "Aunikki", "Aurinko", "Autere", "Autumn", "Bani", "Barbi", "Benedikta", "Beta", "Bigga", "Bio", "Birita",
    "Black", "Caarina", "Caramia", "Chip", "Ciia", "Coca", "Cola", "Colina", "Dakota", "Danica", "Danni", "Demi", "Dove", "Edda", "Eden", "Edina",
    "Edvarda", "Edviina", "Edvina", "Ee", "Eea", "Ela", "Elegia", "Eloisa", "Elsiina", "Emanuela", "Emeliina", "Emeriikka", "Emmanuela", "Ena",
    "Engeliina", "Eni", "Era", "Erenia", "Ernesta", "Esin", "Esse", "Essu", "Este", "Estrella", "Estri", "Eulaalia", "Evette", "Evinka", "Fauna",
    "Felisia", "Feodora", "Floora", "Florensia", "Freesia", "Freialina", "Freija", "Fretriika", "Fretriikka", "Gaby", "Gigi", "Giia", "Gitta", "Goa",
    "Gulveig", "Haija", "Hale", "Halla", "Halme", "Harrietta", "Hawa", "Heikke", "Hela", "Heline", "Helvikki", "Henje", "Hentriikka", "Hera", "Hero",
    "Hetta", "Hillamarja", "Hilli", "Hillu", "Hilme", "Hinne", "Hinriika", "Hinriikka", "Hintriika", "Hintriikka", "Hortensia", "Hymy", "Idalmiina",
    "Ide", "Ihana", "Iive", "Ilinka", "Illusia", "Illuusia", "Ilonka", "Ilsi", "Im", "Ima", "Imma", "Imme", "Immi", "In", "India", "Ineke", "Ingrida",
    "Inker", "Inke", "Inki", "Inkku", "Irenia", "Irenja", "Irinä", "Irmi", "Irmela", "Iro", "Isapella", "Isolda", "Isolde", "Isotta", "Jaa", "Janike",
    "Janka", "Jarita", "Jasmiitta", "Jasminka", "Jasna", "Jeela", "Jemma", "Jen", "Jertta", "Jirina", "Joela", "Joune", "Jovanka", "Joveini", "Juliska",
    "Julitta", "Juni", "Juno", "Juta", "Juuni", "Jöije", "Kaijuli", "Kaika", "Kaisuli", "Kara", "Karissa", "Kariitta", "Karima", "Karliina", "Karoli",
    "Kasmira", "Kaspia", "Kastanja", "Katina", "Katju", "Katjuska", "Katta", "Keema", "Kemi", "Kesa", "Kesä", "Kiamilla", "Kiki", "Killa", "Killu",
    "Kirstiina", "Kirta", "Kissanminttu", "Kitte", "Klementiina", "Klio", "Klotilda", "Konstantina", "Korinna", "Kristella", "Kristiania", "Kristianna",
    "Kuku", "Kulta", "Kunilla", "Kuu", "Kuutar", "Lada", "Lairi", "Lala", "Lalita", "Larita", "Larja", "Lele", "Leliija", "Lelli", "Leonarda", "Leonida",
    "Leontiina", "Letitia", "Letta", "Lexa", "Liana", "Lidja", "Liija", "Liisukka", "Liivia", "Likka", "Linna", "Lippe", "Lispetti", "Lolo", "Lounamilja",
    "Lounatuuli", "Luana", "Lumikirsikka", "Lumilla", "Maarea", "Maarikka", "Maanu", "Maaru", "Madde", "Madilta", "Maeva", "Maisi", "Maisse", "Makko",
    "Malaika", "Malina", "Maliina", "Malka", "Malva", "Malvi", "Mandeliina", "Mandelina", "Mandolina", "Manja", "Mantu", "Manuele", "Manuella", "Mappela",
    "Marenka", "Mareta", "Marilii", "Marite", "Marjinga", "Marjuska", "Marka", "Marli", "Marlia", "Marna", "Mara", "Marsa", "Meela", "Meimei", "Meira",
    "Mekku", "Mele", "Meli", "Melodia", "Melva", "Meme", "Memma", "Memme", "Memmi", "Memmu", "Meni", "Meriella", "Merikeiju", "Merikki", "Merilii",
    "Merilla", "Merisa", "Merje", "Mertsa", "Meta", "Meteoora", "Metsäkeiju", "Metta", "Mianna", "Miija", "Miiju", "Miiru", "Miita", "Mikala", "Mikeli",
    "Mikla", "Miliana", "Militsa", "Miljaana", "Milli", "Milvi", "Mima", "Minki", "Minodora", "Miri", "Miritza", "Mirjaana", "Mirkitta", "Missu",
    "Misu", "Moon", "Mooni", "Muna", "Muru", "Muusa", "Mysi", "Myy", "Nanetta", "Nani", "Nanja", "Nanne", "Nao", "Narja", "Nastasia", "Nastassia",
    "Nata", "Natta", "Neariina", "Neelia", "Nenne", "Nerissa", "Nessa", "Nikka", "Ninetta", "Ninette", "Ninjana", "Ninne", "Nuria", "Nut", "Nuuni",
    "Oilikki", "Oivi", "Oivikki", "Okki", "Oktavia", "Oliva", "Olive", "Olvi", "Omena", "Oneida", "Onja", "Onna", "Onneli", "Orkkuli", "Otteljaana",
    "Ottelia", "Ottiliana", "Pamila", "Pato", "Patria", "Patrisia", "Paule", "Pelleriina", "Peninna", "Penina", "Penni", "Perla", "Pernella", "Petia",
    "Petriikka", "Petrika", "Petrina", "Petrissa", "Piija", "Piiku", "Piippa", "Piita", "Piiti", "Pijatta", "Pikka", "Pikke", "Pille", "Pinne",
    "Pippa", "Pirgitta", "Piri", "Pirja", "Pirjatta", "Pirke", "Pola", "Preeti", "Prikitta", "Priskilla", "Puolukka", "Pupu", "Päikki", "Queen",
    "Raia", "Raiku", "Railikki", "Ramina", "Ranita", "Ranjani", "Reetriika", "Renna", "Retriikka", "Ri", "Riida", "Rikissa", "Rilla", "Ripsa", "Ritja",
    "Roo", "Ru", "Ruu", "Safiira", "Sajatta", "Salle", "Samilla", "Sarala", "Saroja", "Sarolta", "Sarra", "Sarri", "Sateenkaari", "Satumarja", "Satusäde",
    "Saula", "Se", "Sea", "Seeli", "Seelia", "Seena", "Seeri", "Selima", "Sella", "Seni", "Senta", "Serafiima", "Seraina", "Sere", "Seri", "Serene",
    "Seriina", "Sesiilia", "Sesilja", "Si", "Siila", "Sikri", "Silina", "Silvana", "Sine", "Sinikukka", "Sinituuli", "Sinivuokko", "Sinne", "Sirina",
    "Sirka", "Sirki", "Sirkitta", "Siska", "Sistinja", "Skilla", "So", "Sohviia", "Sointi", "Sol", "Sola", "Staava", "Stefani", "Su", "Suleika",
    "Suliina", "Suna", "Sunita", "Sunna", "Sunneva", "Susanka", "Sussa", "Svanni", "Taikakukka", "Taikatuike", "Taikatuuli", "Taila", "Taineli",
    "Taisa", "Talvi", "Tamia", "Tamina", "Tamika", "Tassu", "Teela", "Teia", "Tella", "Teresita", "Tertta", "Tessi", "Tetta", "Tetti", "Ti", "Tiara",
    "Tii", "Tiija", "Tiila", "Tinna", "Tipi", "Tipsa", "Titania", "Titvi", "Tiuhti", "Tiuku", "Tomina", "Tonia", "Triina", "Tuiju", "Tuike", "Tuikku",
    "Tuila", "Tuiti", "Tulikukka", "Tulikki", "Tupuna", "Tutteli", "Tuua", "Tuuva", "Tuuve", "Ulpukka", "Ulrikke", "Ultriikka", "Una", "Une", "Undine",
    "Unni", "Ursule", "Usva", "Vaira", "Valla", "Ware", "Vasilista", "Veeruska", "Viipi", "Viira", "Viiu", "Viiva", "Viivu", "Viljakukka", "Viveke",
    "Xan", "Xena", "Zulu"
    ];

    let name4 = ["Aadaliina", "Aadolfiina", "Aalia", "Aallokki", "Aallokko", "Aamukaste", "Aamunkoi", "Aamurusko", "Aamutuuli", "Aamutähti", "Aana",
    "Aarikka", "Aarna", "Aarnea", "Aarnevi", "Aasia", "Aaluva", "Adelma", "Adolfia", "Adoniikka", "Adora", "Affi", "Africa", "Afrodite", "Agneetta",
    "Agrippiina", "Agrippina", "Agveliina", "Ahava", "Ahkera", "Ai", "Aijali", "Aijeli", "Aijuliina", "Aika", "Ailama", "Ailamo", "Ailikka", "Ainara",
    "Aine", "Aineli", "Aines", "Ainiina", "Ainikka", "Ainoa", "Ainokainen", "Ainokki", "Ainotar", "Ainut", "Airiina", "Aiselu", "Ajatar", "Akaata",
    "Akasia", "Akileia", "Akileija", "Akiliina", "Akillea", "Akita", "Akka", "Akliina", "Akneetta", "Akraseena", "Akselia", "Akseliina", "Aksella",
    "Aksia", "Aksiina", "Aksinja", "Akta", "Akusta", "Akustiina", "Akveliina", "Akviliina", "Albania", "Aldine", "Aleena", "Aleftiina", "Aleksanna",
    "Aleta", "Aletta", "Alexiina", "Alfiina", "Alfriida", "Algi", "Alilla", "Alita", "Alja", "Alkviliina", "Allas", "Allegra", "Alliida", "Almaz",
    "Almiina", "Alna", "Alsine", "Alvia", "Alvira", "Alviira", "Ameli", "Anjussi", "Anneke", "Anseriina", "Anuska", "Arizona", "Arnikki", "Asia",
    "Aspasia", "Atsalea", "Auguste", "Auna", "Aunikki", "Aurinko", "Autere", "Autumn", "Bani", "Barbi", "Benedikta", "Beta", "Bigga", "Bio", "Birita",
    "Black", "Caarina", "Caramia", "Chip", "Ciia", "Coca", "Cola", "Colina", "Dakota", "Danica", "Danni", "Demi", "Dove", "Edda", "Eden", "Edina",
    "Edvarda", "Edviina", "Edvina", "Ee", "Eea", "Ela", "Elegia", "Eloisa", "Elsiina", "Emanuela", "Emeliina", "Emeriikka", "Emmanuela", "Ena",
    "Engeliina", "Eni", "Era", "Erenia", "Ernesta", "Esin", "Esse", "Essu", "Este", "Estrella", "Estri", "Eulaalia", "Evette", "Evinka", "Fauna",
    "Felisia", "Feodora", "Floora", "Florensia", "Freesia", "Freialina", "Freija", "Fretriika", "Fretriikka", "Gaby", "Gigi", "Giia", "Gitta", "Goa",
    "Gulveig", "Haija", "Hale", "Halla", "Halme", "Harrietta", "Hawa", "Heikke", "Hela", "Heline", "Helvikki", "Henje", "Hentriikka", "Hera", "Hero",
    "Hetta", "Hillamarja", "Hilli", "Hillu", "Hilme", "Hinne", "Hinriika", "Hinriikka", "Hintriika", "Hintriikka", "Hortensia", "Hymy", "Idalmiina",
    "Ide", "Ihana", "Iive", "Ilinka", "Illusia", "Illuusia", "Ilonka", "Ilsi", "Im", "Ima", "Imma", "Imme", "Immi", "In", "India", "Ineke", "Ingrida",
    "Inker", "Inke", "Inki", "Inkku", "Irenia", "Irenja", "Irinä", "Irmi", "Irmela", "Iro", "Isapella", "Isolda", "Isolde", "Isotta", "Jaa", "Janike",
    "Janka", "Jarita", "Jasmiitta", "Jasminka", "Jasna", "Jeela", "Jemma", "Jen", "Jertta", "Jirina", "Joela", "Joune", "Jovanka", "Joveini", "Juliska",
    "Julitta", "Juni", "Juno", "Juta", "Juuni", "Jöije", "Kaijuli", "Kaika", "Kaisuli", "Kara", "Karissa", "Kariitta", "Karima", "Karliina", "Karoli",
    "Kasmira", "Kaspia", "Kastanja", "Katina", "Katju", "Katjuska", "Katta", "Keema", "Kemi", "Kesa", "Kesä", "Kiamilla", "Kiki", "Killa", "Killu",
    "Kirstiina", "Kirta", "Kissanminttu", "Kitte", "Klementiina", "Klio", "Klotilda", "Konstantina", "Korinna", "Kristella", "Kristiania", "Kristianna",
    "Kuku", "Kulta", "Kunilla", "Kuu", "Kuutar", "Lada", "Lairi", "Lala", "Lalita", "Larita", "Larja", "Lele", "Leliija", "Lelli", "Leonarda", "Leonida",
    "Leontiina", "Letitia", "Letta", "Lexa", "Liana", "Lidja", "Liija", "Liisukka", "Liivia", "Likka", "Linna", "Lippe", "Lispetti", "Lolo", "Lounamilja",
    "Lounatuuli", "Luana", "Lumikirsikka", "Lumilla", "Maarea", "Maarikka", "Maanu", "Maaru", "Madde", "Madilta", "Maeva", "Maisi", "Maisse", "Makko",
    "Malaika", "Malina", "Maliina", "Malka", "Malva", "Malvi", "Mandeliina", "Mandelina", "Mandolina", "Manja", "Mantu", "Manuele", "Manuella", "Mappela",
    "Marenka", "Mareta", "Marilii", "Marite", "Marjinga", "Marjuska", "Marka", "Marli", "Marlia", "Marna", "Mara", "Marsa", "Meela", "Meimei", "Meira",
    "Mekku", "Mele", "Meli", "Melodia", "Melva", "Meme", "Memma", "Memme", "Memmi", "Memmu", "Meni", "Meriella", "Merikeiju", "Merikki", "Merilii",
    "Merilla", "Merisa", "Merje", "Mertsa", "Meta", "Meteoora", "Metsäkeiju", "Metta", "Mianna", "Miija", "Miiju", "Miiru", "Miita", "Mikala", "Mikeli",
    "Mikla", "Miliana", "Militsa", "Miljaana", "Milli", "Milvi", "Mima", "Minki", "Minodora", "Miri", "Miritza", "Mirjaana", "Mirkitta", "Missu",
    "Misu", "Moon", "Mooni", "Muna", "Muru", "Muusa", "Mysi", "Myy", "Nanetta", "Nani", "Nanja", "Nanne", "Nao", "Narja", "Nastasia", "Nastassia",
    "Nata", "Natta", "Neariina", "Neelia", "Nenne", "Nerissa", "Nessa", "Nikka", "Ninetta", "Ninette", "Ninjana", "Ninne", "Nuria", "Nut", "Nuuni",
    "Oilikki", "Oivi", "Oivikki", "Okki", "Oktavia", "Oliva", "Olive", "Olvi", "Omena", "Oneida", "Onja", "Onna", "Onneli", "Orkkuli", "Otteljaana",
    "Ottelia", "Ottiliana", "Pamila", "Pato", "Patria", "Patrisia", "Paule", "Pelleriina", "Peninna", "Penina", "Penni", "Perla", "Pernella", "Petia",
    "Petriikka", "Petrika", "Petrina", "Petrissa", "Piija", "Piiku", "Piippa", "Piita", "Piiti", "Pijatta", "Pikka", "Pikke", "Pille", "Pinne",
    "Pippa", "Pirgitta", "Piri", "Pirja", "Pirjatta", "Pirke", "Pola", "Preeti", "Prikitta", "Priskilla", "Puolukka", "Pupu", "Päikki", "Queen",
    "Raia", "Raiku", "Railikki", "Ramina", "Ranita", "Ranjani", "Reetriika", "Renna", "Retriikka", "Ri", "Riida", "Rikissa", "Rilla", "Ripsa", "Ritja",
    "Roo", "Ru", "Ruu", "Safiira", "Sajatta", "Salle", "Samilla", "Sarala", "Saroja", "Sarolta", "Sarra", "Sarri", "Sateenkaari", "Satumarja", "Satusäde",
    "Saula", "Se", "Sea", "Seeli", "Seelia", "Seena", "Seeri", "Selima", "Sella", "Seni", "Senta", "Serafiima", "Seraina", "Sere", "Seri", "Serene",
    "Seriina", "Sesiilia", "Sesilja", "Si", "Siila", "Sikri", "Silina", "Silvana", "Sine", "Sinikukka", "Sinituuli", "Sinivuokko", "Sinne", "Sirina",
    "Sirka", "Sirki", "Sirkitta", "Siska", "Sistinja", "Skilla", "So", "Sohviia", "Sointi", "Sol", "Sola", "Staava", "Stefani", "Su", "Suleika",
    "Suliina", "Suna", "Sunita", "Sunna", "Sunneva", "Susanka", "Sussa", "Svanni", "Taikakukka", "Taikatuike", "Taikatuuli", "Taila", "Taineli",
    "Taisa", "Talvi", "Tamia", "Tamina", "Tamika", "Tassu", "Teela", "Teia", "Tella", "Teresita", "Tertta", "Tessi", "Tetta", "Tetti", "Ti", "Tiara",
    "Tii", "Tiija", "Tiila", "Tinna", "Tipi", "Tipsa", "Titania", "Titvi", "Tiuhti", "Tiuku", "Tomina", "Tonia", "Triina", "Tuiju", "Tuike", "Tuikku",
    "Tuila", "Tuiti", "Tulikukka", "Tulikki", "Tupuna", "Tutteli", "Tuua", "Tuuva", "Tuuve", "Ulpukka", "Ulrikke", "Ultriikka", "Una", "Une", "Undine",
    "Unni", "Ursule", "Usva", "Vaira", "Valla", "Ware", "Vasilista", "Veeruska", "Viipi", "Viira", "Viiu", "Viiva", "Viivu", "Viljakukka", "Viveke",
    "Xan", "Xena", "Zulu"
    ];

    let randomNameF = name3[Math.floor(Math.random() * name3.length)] + " " + name4[Math.floor(Math.random() * name4.length)];

    alert(randomNameF);
}

function generatorFM(){
    let name5 = ["Aabeli", "Aabi", "Aabrahami", "Aahas", "Aalikki", "Aamen", "Aamunvalo", "Aaprahami", "Aapru", "Aarikki", "Aarmo", "Aarnetti",
    "Aarnoltti", "Aarres", "Aarretti", "Aarro", "Aarti", "Aartsi", "Aarttu", "Aateli", "Aato", "Aatolvi", "Aatsa", "Aatso", "Aatte", "Aattu",
    "Aaveli", "Aavo", "Abrami", "Adonis", "Aetius", "Afrika", "Ahas", "Ahde", "Ahma", "Ahmo", "Ahtu", "Ahve", "Aihe", "Aikamies", "Aikio", "Aikko",
    "Ailu", "Aimone", "Ainar", "Ainu", "Airamo", "Airik", "Airikka", "Airo", "Aivo", "Ajax", "Akatius", "Akke", "Akki", "Akse", "Alaattin", "Alanen",
    "Alari", "Alas", "Albertto", "Alemu", "Alermi", "Alessi", "Alexsanderi", "Alister", "Alkio", "Alkki", "Allah", "Alle", "Allo", "Almar", "Almer",
    "Almi", "Almus", "Alonso", "Alvaro", "Alve", "Amadeo", "Anakin", "Anatolius", "Andreevits", "Anse", "Anselmo", "Ansi", "Antte", "Aaprahami", "Aprami",
    "Arssi", "Artturo", "Arvidi", "Arviidi", "Arviitti", "Askur", "Askuri", "Aslo", "Assari", "Ater", "Atta", "Atti", "Atto", "Attu", "Autere", "Ax",
    "Babar", "Bani", "Beni", "Benedikt", "Black", "Borg", "Chip", "Cicero", "Cosmo", "Dino", "Dublin", "Ee", "Eepo", "Eerikka", "Ekke", "Ekko", "Ekku",
    "Elbertti", "Ele", "Eleasar", "Elio", "Elmari", "Enno", "Ennu", "Enska", "Enso", "Enti", "Erasmus", "Era", "Ertti", "Ertto", "Erve", "Ervi", "Esse",
    "Feeli", "Ford", "Fredrikki", "Freetrikki", "Gigi", "Gil", "Golf", "Halo", "Halvar", "Hami", "Halmet", "Hannibal", "Hansi", "Hartti", "Hassel",
    "Heikka", "Heikkijaakko", "Heka", "Hemi", "Hemo", "Hentrik", "Hentrikki", "Herkules", "Hermes", "Herne", "Hese", "Hilari", "Hillari", "Hilmo",
    "Hirvo", "Hole", "Homo", "Huoti", "Huvi", "Ii", "Iippo", "Iisku", "Ilias", "Ilves", "Im", "Ima", "Immu", "Inko", "Iska", "Ismari", "Ispo", "Itu",
    "Jaakop", "Jaapo", "Jaarli", "Jahvet", "Jaki", "Jame", "Janke", "Janko", "Jante", "Janus", "Jasa", "Jaspar", "Jedi", "Jeemi", "Jehki", "Jemi",
    "Jerkka", "Jermo", "Jimmi", "Jirik", "Joa", "Johani", "Jormo", "Jouhki", "Joulu", "Joutsi", "Juhi", "Juksu", "Junias", "Junne", "Jupiter", "Jöri",
    "Ka", "Kaa", "Kaapre", "Kaapri", "Kaike", "Kaiko", "Kaiku", "Kaima", "Kake", "Kale", "Kallu", "Karma", "Kaspari", "Kaspian", "Kassius", "Kauppi",
    "Kauppo", "Keemo", "Keke", "Kelvin", "Kem", "Kermit", "Kermo", "Kilu", "Kirka", "Kirmo", "Kiwi", "Klaes", "Klementti", "Kliment", "Knuut", "Knuuti",
    "Knuutti", "Kontio", "Kontro", "Kornelius", "Kosma", "Kostja", "Kouta", "Kuku", "Kössi", "Lalo", "Lalu", "Lamperi", "Lampertti", "Lappi", "Leiffi",
    "Leksa", "Lexa", "Len", "Lennartti", "Lennu", "Leonartti", "Leva", "Leve", "Levo", "Liimo", "Lode", "Makari", "Makko", "Maks", "Maksimilian", "Mane",
    "Mani", "Mano", "Manuele", "Manueli", "Marno", "Marton", "Massi", "Mauritius", "Menno", "Meo", "Meritre", "Miihka", "Miihkali", "Miikkali", "Miikkula",
    "Miio", "Miitra", "Miitre", "Miitro", "Mikali", "Mikka", "Mikkal", "Miklas", "Miklo", "Miklos", "Mikos", "Moon", "Moosa", "Moose", "Morits", "Moriz",
    "Morton", "Mortti", "Musta", "Nadi", "Nakke", "Nandor", "Nathanael", "Ned", "Nemo", "Niikko", "Niilas", "Niilles", "Nikki", "Niky", "Nikko", "Niklaus",
    "Nilas", "Nio", "Nipa", "Noeli", "Nuo", "Nut", "Nuu", "Nuuti", "Obelix", "Obi", "Ohvo", "Okka", "Okke", "Oksu", "Olai", "Olaus", "Oleksei", "Oleksi",
    "Oli", "One", "Ontrei", "Ontro", "Ooke", "Opal", "Optatus", "Ora", "Ore", "Orko", "Orri", "Orvar", "Osa", "Oska", "Oski", "Oso", "Osvi", "Otmar",
    "Otro", "Oulas", "Ouli", "Pate", "Patri", "Patrikki", "Patro", "Patu", "Paulos", "Pauni", "Paunu", "Pave", "Pavo", "Peer", "Peeti", "Peitsa", "Pekki", 
    "Peko", "Pellonpekko", "Pena", "Penhartti", "Penjam", "Penna", "Pera", "Perttyli", "Peteris", "Petka", "Petros", "Peetu", "Pieti", "Poul", "Primo",
    "Prokko", "Rainar", "Raito", "Ralfe", "Ramana", "Ramani", "Ramine", "Rane", "Ransu", "Rasmu", "Ree", "Reetu", "Rego", "Reimar", "Reimer", "Reimo",
    "Reinar", "Reinari", "Reinart", "Reinhart", "Remi", "Remo", "Renni", "Repa", "Repe", "Retu", "Revontuli", "Ri", "Rieti", "Rietrikki", "Rietu",
    "Rihko", "Riiko", "Rike", "Rikhartti", "Rikke", "Ro", "Rollo", "Ronni", "Rono", "Roo", "Ru", "Ruu", "Ruupertti", "Ruurikki", "Saammal", "Sakkeus",
    "Sakris", "Salle", "Sammi", "Sammo", "Sammu", "Samo", "Sante", "Santero", "Saulo", "Savi", "Sees", "Seikko", "Semio", "Senior", "Senori", "Sepe",
    "Sepeteus", "Seppi", "Serko", "Sero", "Si", "Sihvertti", "Siilas", "Siinto", "Silvester", "Simana", "Simojussi", "Simopekka", "Simppa", "Simuna",
    "Sing", "So", "Stanislaus", "Stefanos", "Stepanus", "Su", "Tarkko", "Tauri", "Tauvo", "Terenti", "Teutori", "Tiera", "Tihvo", "Tiikka", "Timitri",
    "Timjam", "Timjami", "Timka", "Timotei", "Toffee", "Tommo", "Ugu", "Uke", "Uki", "Uko", "Ukri", "Uku", "Ulias", "Unne", "Unski", "Uule", "Valentinus",
    "Valko", "Valta", "Valton", "Valtti", "Vangs", "Vante", "Vantte", "Vasilli", "Veeliks", "Well", "White", "Vikki", "Vilkko", "Villehart", "Villi",
    "Vilmari", "Vilmeri", "Vilppo", "Vittorio", "Volte", "Vulle", "Väinämöinen", "Ykä", "Yrmy", "Yö", "Zeus", "Örkki", "Aadaliina", "Aadolfiina", "Aalia", "Aallokki", "Aallokko", "Aamukaste", "Aamunkoi", "Aamurusko", "Aamutuuli", "Aamutähti", "Aana",
    "Aarikka", "Aarna", "Aarnea", "Aarnevi", "Aasia", "Aaluva", "Adelma", "Adolfia", "Adoniikka", "Adora", "Affi", "Africa", "Afrodite", "Agneetta",
    "Agrippiina", "Agrippina", "Agveliina", "Ahava", "Ahkera", "Ai", "Aijali", "Aijeli", "Aijuliina", "Aika", "Ailama", "Ailamo", "Ailikka", "Ainara",
    "Aine", "Aineli", "Aines", "Ainiina", "Ainikka", "Ainoa", "Ainokainen", "Ainokki", "Ainotar", "Ainut", "Airiina", "Aiselu", "Ajatar", "Akaata",
    "Akasia", "Akileia", "Akileija", "Akiliina", "Akillea", "Akita", "Akka", "Akliina", "Akneetta", "Akraseena", "Akselia", "Akseliina", "Aksella",
    "Aksia", "Aksiina", "Aksinja", "Akta", "Akusta", "Akustiina", "Akveliina", "Akviliina", "Albania", "Aldine", "Aleena", "Aleftiina", "Aleksanna",
    "Aleta", "Aletta", "Alexiina", "Alfiina", "Alfriida", "Algi", "Alilla", "Alita", "Alja", "Alkviliina", "Allas", "Allegra", "Alliida", "Almaz",
    "Almiina", "Alna", "Alsine", "Alvia", "Alvira", "Alviira", "Ameli", "Anjussi", "Anneke", "Anseriina", "Anuska", "Arizona", "Arnikki", "Asia",
    "Aspasia", "Atsalea", "Auguste", "Auna", "Aunikki", "Aurinko", "Autere", "Autumn", "Bani", "Barbi", "Benedikta", "Beta", "Bigga", "Bio", "Birita",
    "Black", "Caarina", "Caramia", "Chip", "Ciia", "Coca", "Cola", "Colina", "Dakota", "Danica", "Danni", "Demi", "Dove", "Edda", "Eden", "Edina",
    "Edvarda", "Edviina", "Edvina", "Ee", "Eea", "Ela", "Elegia", "Eloisa", "Elsiina", "Emanuela", "Emeliina", "Emeriikka", "Emmanuela", "Ena",
    "Engeliina", "Eni", "Era", "Erenia", "Ernesta", "Esin", "Esse", "Essu", "Este", "Estrella", "Estri", "Eulaalia", "Evette", "Evinka", "Fauna",
    "Felisia", "Feodora", "Floora", "Florensia", "Freesia", "Freialina", "Freija", "Fretriika", "Fretriikka", "Gaby", "Gigi", "Giia", "Gitta", "Goa",
    "Gulveig", "Haija", "Hale", "Halla", "Halme", "Harrietta", "Hawa", "Heikke", "Hela", "Heline", "Helvikki", "Henje", "Hentriikka", "Hera", "Hero",
    "Hetta", "Hillamarja", "Hilli", "Hillu", "Hilme", "Hinne", "Hinriika", "Hinriikka", "Hintriika", "Hintriikka", "Hortensia", "Hymy", "Idalmiina",
    "Ide", "Ihana", "Iive", "Ilinka", "Illusia", "Illuusia", "Ilonka", "Ilsi", "Im", "Ima", "Imma", "Imme", "Immi", "In", "India", "Ineke", "Ingrida",
    "Inker", "Inke", "Inki", "Inkku", "Irenia", "Irenja", "Irinä", "Irmi", "Irmela", "Iro", "Isapella", "Isolda", "Isolde", "Isotta", "Jaa", "Janike",
    "Janka", "Jarita", "Jasmiitta", "Jasminka", "Jasna", "Jeela", "Jemma", "Jen", "Jertta", "Jirina", "Joela", "Joune", "Jovanka", "Joveini", "Juliska",
    "Julitta", "Juni", "Juno", "Juta", "Juuni", "Jöije", "Kaijuli", "Kaika", "Kaisuli", "Kara", "Karissa", "Kariitta", "Karima", "Karliina", "Karoli",
    "Kasmira", "Kaspia", "Kastanja", "Katina", "Katju", "Katjuska", "Katta", "Keema", "Kemi", "Kesa", "Kesä", "Kiamilla", "Kiki", "Killa", "Killu",
    "Kirstiina", "Kirta", "Kissanminttu", "Kitte", "Klementiina", "Klio", "Klotilda", "Konstantina", "Korinna", "Kristella", "Kristiania", "Kristianna",
    "Kuku", "Kulta", "Kunilla", "Kuu", "Kuutar", "Lada", "Lairi", "Lala", "Lalita", "Larita", "Larja", "Lele", "Leliija", "Lelli", "Leonarda", "Leonida",
    "Leontiina", "Letitia", "Letta", "Lexa", "Liana", "Lidja", "Liija", "Liisukka", "Liivia", "Likka", "Linna", "Lippe", "Lispetti", "Lolo", "Lounamilja",
    "Lounatuuli", "Luana", "Lumikirsikka", "Lumilla", "Maarea", "Maarikka", "Maanu", "Maaru", "Madde", "Madilta", "Maeva", "Maisi", "Maisse", "Makko",
    "Malaika", "Malina", "Maliina", "Malka", "Malva", "Malvi", "Mandeliina", "Mandelina", "Mandolina", "Manja", "Mantu", "Manuele", "Manuella", "Mappela",
    "Marenka", "Mareta", "Marilii", "Marite", "Marjinga", "Marjuska", "Marka", "Marli", "Marlia", "Marna", "Mara", "Marsa", "Meela", "Meimei", "Meira",
    "Mekku", "Mele", "Meli", "Melodia", "Melva", "Meme", "Memma", "Memme", "Memmi", "Memmu", "Meni", "Meriella", "Merikeiju", "Merikki", "Merilii",
    "Merilla", "Merisa", "Merje", "Mertsa", "Meta", "Meteoora", "Metsäkeiju", "Metta", "Mianna", "Miija", "Miiju", "Miiru", "Miita", "Mikala", "Mikeli",
    "Mikla", "Miliana", "Militsa", "Miljaana", "Milli", "Milvi", "Mima", "Minki", "Minodora", "Miri", "Miritza", "Mirjaana", "Mirkitta", "Missu",
    "Misu", "Moon", "Mooni", "Muna", "Muru", "Muusa", "Mysi", "Myy", "Nanetta", "Nani", "Nanja", "Nanne", "Nao", "Narja", "Nastasia", "Nastassia",
    "Nata", "Natta", "Neariina", "Neelia", "Nenne", "Nerissa", "Nessa", "Nikka", "Ninetta", "Ninette", "Ninjana", "Ninne", "Nuria", "Nut", "Nuuni",
    "Oilikki", "Oivi", "Oivikki", "Okki", "Oktavia", "Oliva", "Olive", "Olvi", "Omena", "Oneida", "Onja", "Onna", "Onneli", "Orkkuli", "Otteljaana",
    "Ottelia", "Ottiliana", "Pamila", "Pato", "Patria", "Patrisia", "Paule", "Pelleriina", "Peninna", "Penina", "Penni", "Perla", "Pernella", "Petia",
    "Petriikka", "Petrika", "Petrina", "Petrissa", "Piija", "Piiku", "Piippa", "Piita", "Piiti", "Pijatta", "Pikka", "Pikke", "Pille", "Pinne",
    "Pippa", "Pirgitta", "Piri", "Pirja", "Pirjatta", "Pirke", "Pola", "Preeti", "Prikitta", "Priskilla", "Puolukka", "Pupu", "Päikki", "Queen",
    "Raia", "Raiku", "Railikki", "Ramina", "Ranita", "Ranjani", "Reetriika", "Renna", "Retriikka", "Ri", "Riida", "Rikissa", "Rilla", "Ripsa", "Ritja",
    "Roo", "Ru", "Ruu", "Safiira", "Sajatta", "Salle", "Samilla", "Sarala", "Saroja", "Sarolta", "Sarra", "Sarri", "Sateenkaari", "Satumarja", "Satusäde",
    "Saula", "Se", "Sea", "Seeli", "Seelia", "Seena", "Seeri", "Selima", "Sella", "Seni", "Senta", "Serafiima", "Seraina", "Sere", "Seri", "Serene",
    "Seriina", "Sesiilia", "Sesilja", "Si", "Siila", "Sikri", "Silina", "Silvana", "Sine", "Sinikukka", "Sinituuli", "Sinivuokko", "Sinne", "Sirina",
    "Sirka", "Sirki", "Sirkitta", "Siska", "Sistinja", "Skilla", "So", "Sohviia", "Sointi", "Sol", "Sola", "Staava", "Stefani", "Su", "Suleika",
    "Suliina", "Suna", "Sunita", "Sunna", "Sunneva", "Susanka", "Sussa", "Svanni", "Taikakukka", "Taikatuike", "Taikatuuli", "Taila", "Taineli",
    "Taisa", "Talvi", "Tamia", "Tamina", "Tamika", "Tassu", "Teela", "Teia", "Tella", "Teresita", "Tertta", "Tessi", "Tetta", "Tetti", "Ti", "Tiara",
    "Tii", "Tiija", "Tiila", "Tinna", "Tipi", "Tipsa", "Titania", "Titvi", "Tiuhti", "Tiuku", "Tomina", "Tonia", "Triina", "Tuiju", "Tuike", "Tuikku",
    "Tuila", "Tuiti", "Tulikukka", "Tulikki", "Tupuna", "Tutteli", "Tuua", "Tuuva", "Tuuve", "Ulpukka", "Ulrikke", "Ultriikka", "Una", "Une", "Undine",
    "Unni", "Ursule", "Usva", "Vaira", "Valla", "Ware", "Vasilista", "Veeruska", "Viipi", "Viira", "Viiu", "Viiva", "Viivu", "Viljakukka", "Viveke",
    "Xan", "Xena", "Zulu"];

    let name6 = ["Aabeli", "Aabi", "Aabrahami", "Aahas", "Aalikki", "Aamen", "Aamunvalo", "Aaprahami", "Aapru", "Aarikki", "Aarmo", "Aarnetti",
    "Aarnoltti", "Aarres", "Aarretti", "Aarro", "Aarti", "Aartsi", "Aarttu", "Aateli", "Aato", "Aatolvi", "Aatsa", "Aatso", "Aatte", "Aattu",
    "Aaveli", "Aavo", "Abrami", "Adonis", "Aetius", "Afrika", "Ahas", "Ahde", "Ahma", "Ahmo", "Ahtu", "Ahve", "Aihe", "Aikamies", "Aikio", "Aikko",
    "Ailu", "Aimone", "Ainar", "Ainu", "Airamo", "Airik", "Airikka", "Airo", "Aivo", "Ajax", "Akatius", "Akke", "Akki", "Akse", "Alaattin", "Alanen",
    "Alari", "Alas", "Albertto", "Alemu", "Alermi", "Alessi", "Alexsanderi", "Alister", "Alkio", "Alkki", "Allah", "Alle", "Allo", "Almar", "Almer",
    "Almi", "Almus", "Alonso", "Alvaro", "Alve", "Amadeo", "Anakin", "Anatolius", "Andreevits", "Anse", "Anselmo", "Ansi", "Antte", "Aaprahami", "Aprami",
    "Arssi", "Artturo", "Arvidi", "Arviidi", "Arviitti", "Askur", "Askuri", "Aslo", "Assari", "Ater", "Atta", "Atti", "Atto", "Attu", "Autere", "Ax",
    "Babar", "Bani", "Beni", "Benedikt", "Black", "Borg", "Chip", "Cicero", "Cosmo", "Dino", "Dublin", "Ee", "Eepo", "Eerikka", "Ekke", "Ekko", "Ekku",
    "Elbertti", "Ele", "Eleasar", "Elio", "Elmari", "Enno", "Ennu", "Enska", "Enso", "Enti", "Erasmus", "Era", "Ertti", "Ertto", "Erve", "Ervi", "Esse",
    "Feeli", "Ford", "Fredrikki", "Freetrikki", "Gigi", "Gil", "Golf", "Halo", "Halvar", "Hami", "Halmet", "Hannibal", "Hansi", "Hartti", "Hassel",
    "Heikka", "Heikkijaakko", "Heka", "Hemi", "Hemo", "Hentrik", "Hentrikki", "Herkules", "Hermes", "Herne", "Hese", "Hilari", "Hillari", "Hilmo",
    "Hirvo", "Hole", "Homo", "Huoti", "Huvi", "Ii", "Iippo", "Iisku", "Ilias", "Ilves", "Im", "Ima", "Immu", "Inko", "Iska", "Ismari", "Ispo", "Itu",
    "Jaakop", "Jaapo", "Jaarli", "Jahvet", "Jaki", "Jame", "Janke", "Janko", "Jante", "Janus", "Jasa", "Jaspar", "Jedi", "Jeemi", "Jehki", "Jemi",
    "Jerkka", "Jermo", "Jimmi", "Jirik", "Joa", "Johani", "Jormo", "Jouhki", "Joulu", "Joutsi", "Juhi", "Juksu", "Junias", "Junne", "Jupiter", "Jöri",
    "Ka", "Kaa", "Kaapre", "Kaapri", "Kaike", "Kaiko", "Kaiku", "Kaima", "Kake", "Kale", "Kallu", "Karma", "Kaspari", "Kaspian", "Kassius", "Kauppi",
    "Kauppo", "Keemo", "Keke", "Kelvin", "Kem", "Kermit", "Kermo", "Kilu", "Kirka", "Kirmo", "Kiwi", "Klaes", "Klementti", "Kliment", "Knuut", "Knuuti",
    "Knuutti", "Kontio", "Kontro", "Kornelius", "Kosma", "Kostja", "Kouta", "Kuku", "Kössi", "Lalo", "Lalu", "Lamperi", "Lampertti", "Lappi", "Leiffi",
    "Leksa", "Lexa", "Len", "Lennartti", "Lennu", "Leonartti", "Leva", "Leve", "Levo", "Liimo", "Lode", "Makari", "Makko", "Maks", "Maksimilian", "Mane",
    "Mani", "Mano", "Manuele", "Manueli", "Marno", "Marton", "Massi", "Mauritius", "Menno", "Meo", "Meritre", "Miihka", "Miihkali", "Miikkali", "Miikkula",
    "Miio", "Miitra", "Miitre", "Miitro", "Mikali", "Mikka", "Mikkal", "Miklas", "Miklo", "Miklos", "Mikos", "Moon", "Moosa", "Moose", "Morits", "Moriz",
    "Morton", "Mortti", "Musta", "Nadi", "Nakke", "Nandor", "Nathanael", "Ned", "Nemo", "Niikko", "Niilas", "Niilles", "Nikki", "Niky", "Nikko", "Niklaus",
    "Nilas", "Nio", "Nipa", "Noeli", "Nuo", "Nut", "Nuu", "Nuuti", "Obelix", "Obi", "Ohvo", "Okka", "Okke", "Oksu", "Olai", "Olaus", "Oleksei", "Oleksi",
    "Oli", "One", "Ontrei", "Ontro", "Ooke", "Opal", "Optatus", "Ora", "Ore", "Orko", "Orri", "Orvar", "Osa", "Oska", "Oski", "Oso", "Osvi", "Otmar",
    "Otro", "Oulas", "Ouli", "Pate", "Patri", "Patrikki", "Patro", "Patu", "Paulos", "Pauni", "Paunu", "Pave", "Pavo", "Peer", "Peeti", "Peitsa", "Pekki", 
    "Peko", "Pellonpekko", "Pena", "Penhartti", "Penjam", "Penna", "Pera", "Perttyli", "Peteris", "Petka", "Petros", "Peetu", "Pieti", "Poul", "Primo",
    "Prokko", "Rainar", "Raito", "Ralfe", "Ramana", "Ramani", "Ramine", "Rane", "Ransu", "Rasmu", "Ree", "Reetu", "Rego", "Reimar", "Reimer", "Reimo",
    "Reinar", "Reinari", "Reinart", "Reinhart", "Remi", "Remo", "Renni", "Repa", "Repe", "Retu", "Revontuli", "Ri", "Rieti", "Rietrikki", "Rietu",
    "Rihko", "Riiko", "Rike", "Rikhartti", "Rikke", "Ro", "Rollo", "Ronni", "Rono", "Roo", "Ru", "Ruu", "Ruupertti", "Ruurikki", "Saammal", "Sakkeus",
    "Sakris", "Salle", "Sammi", "Sammo", "Sammu", "Samo", "Sante", "Santero", "Saulo", "Savi", "Sees", "Seikko", "Semio", "Senior", "Senori", "Sepe",
    "Sepeteus", "Seppi", "Serko", "Sero", "Si", "Sihvertti", "Siilas", "Siinto", "Silvester", "Simana", "Simojussi", "Simopekka", "Simppa", "Simuna",
    "Sing", "So", "Stanislaus", "Stefanos", "Stepanus", "Su", "Tarkko", "Tauri", "Tauvo", "Terenti", "Teutori", "Tiera", "Tihvo", "Tiikka", "Timitri",
    "Timjam", "Timjami", "Timka", "Timotei", "Toffee", "Tommo", "Ugu", "Uke", "Uki", "Uko", "Ukri", "Uku", "Ulias", "Unne", "Unski", "Uule", "Valentinus",
    "Valko", "Valta", "Valton", "Valtti", "Vangs", "Vante", "Vantte", "Vasilli", "Veeliks", "Well", "White", "Vikki", "Vilkko", "Villehart", "Villi",
    "Vilmari", "Vilmeri", "Vilppo", "Vittorio", "Volte", "Vulle", "Väinämöinen", "Ykä", "Yrmy", "Yö", "Zeus", "Örkki", "Aadaliina", "Aadolfiina", "Aalia", "Aallokki", "Aallokko", "Aamukaste", "Aamunkoi", "Aamurusko", "Aamutuuli", "Aamutähti", "Aana",
    "Aarikka", "Aarna", "Aarnea", "Aarnevi", "Aasia", "Aaluva", "Adelma", "Adolfia", "Adoniikka", "Adora", "Affi", "Africa", "Afrodite", "Agneetta",
    "Agrippiina", "Agrippina", "Agveliina", "Ahava", "Ahkera", "Ai", "Aijali", "Aijeli", "Aijuliina", "Aika", "Ailama", "Ailamo", "Ailikka", "Ainara",
    "Aine", "Aineli", "Aines", "Ainiina", "Ainikka", "Ainoa", "Ainokainen", "Ainokki", "Ainotar", "Ainut", "Airiina", "Aiselu", "Ajatar", "Akaata",
    "Akasia", "Akileia", "Akileija", "Akiliina", "Akillea", "Akita", "Akka", "Akliina", "Akneetta", "Akraseena", "Akselia", "Akseliina", "Aksella",
    "Aksia", "Aksiina", "Aksinja", "Akta", "Akusta", "Akustiina", "Akveliina", "Akviliina", "Albania", "Aldine", "Aleena", "Aleftiina", "Aleksanna",
    "Aleta", "Aletta", "Alexiina", "Alfiina", "Alfriida", "Algi", "Alilla", "Alita", "Alja", "Alkviliina", "Allas", "Allegra", "Alliida", "Almaz",
    "Almiina", "Alna", "Alsine", "Alvia", "Alvira", "Alviira", "Ameli", "Anjussi", "Anneke", "Anseriina", "Anuska", "Arizona", "Arnikki", "Asia",
    "Aspasia", "Atsalea", "Auguste", "Auna", "Aunikki", "Aurinko", "Autere", "Autumn", "Bani", "Barbi", "Benedikta", "Beta", "Bigga", "Bio", "Birita",
    "Black", "Caarina", "Caramia", "Chip", "Ciia", "Coca", "Cola", "Colina", "Dakota", "Danica", "Danni", "Demi", "Dove", "Edda", "Eden", "Edina",
    "Edvarda", "Edviina", "Edvina", "Ee", "Eea", "Ela", "Elegia", "Eloisa", "Elsiina", "Emanuela", "Emeliina", "Emeriikka", "Emmanuela", "Ena",
    "Engeliina", "Eni", "Era", "Erenia", "Ernesta", "Esin", "Esse", "Essu", "Este", "Estrella", "Estri", "Eulaalia", "Evette", "Evinka", "Fauna",
    "Felisia", "Feodora", "Floora", "Florensia", "Freesia", "Freialina", "Freija", "Fretriika", "Fretriikka", "Gaby", "Gigi", "Giia", "Gitta", "Goa",
    "Gulveig", "Haija", "Hale", "Halla", "Halme", "Harrietta", "Hawa", "Heikke", "Hela", "Heline", "Helvikki", "Henje", "Hentriikka", "Hera", "Hero",
    "Hetta", "Hillamarja", "Hilli", "Hillu", "Hilme", "Hinne", "Hinriika", "Hinriikka", "Hintriika", "Hintriikka", "Hortensia", "Hymy", "Idalmiina",
    "Ide", "Ihana", "Iive", "Ilinka", "Illusia", "Illuusia", "Ilonka", "Ilsi", "Im", "Ima", "Imma", "Imme", "Immi", "In", "India", "Ineke", "Ingrida",
    "Inker", "Inke", "Inki", "Inkku", "Irenia", "Irenja", "Irinä", "Irmi", "Irmela", "Iro", "Isapella", "Isolda", "Isolde", "Isotta", "Jaa", "Janike",
    "Janka", "Jarita", "Jasmiitta", "Jasminka", "Jasna", "Jeela", "Jemma", "Jen", "Jertta", "Jirina", "Joela", "Joune", "Jovanka", "Joveini", "Juliska",
    "Julitta", "Juni", "Juno", "Juta", "Juuni", "Jöije", "Kaijuli", "Kaika", "Kaisuli", "Kara", "Karissa", "Kariitta", "Karima", "Karliina", "Karoli",
    "Kasmira", "Kaspia", "Kastanja", "Katina", "Katju", "Katjuska", "Katta", "Keema", "Kemi", "Kesa", "Kesä", "Kiamilla", "Kiki", "Killa", "Killu",
    "Kirstiina", "Kirta", "Kissanminttu", "Kitte", "Klementiina", "Klio", "Klotilda", "Konstantina", "Korinna", "Kristella", "Kristiania", "Kristianna",
    "Kuku", "Kulta", "Kunilla", "Kuu", "Kuutar", "Lada", "Lairi", "Lala", "Lalita", "Larita", "Larja", "Lele", "Leliija", "Lelli", "Leonarda", "Leonida",
    "Leontiina", "Letitia", "Letta", "Lexa", "Liana", "Lidja", "Liija", "Liisukka", "Liivia", "Likka", "Linna", "Lippe", "Lispetti", "Lolo", "Lounamilja",
    "Lounatuuli", "Luana", "Lumikirsikka", "Lumilla", "Maarea", "Maarikka", "Maanu", "Maaru", "Madde", "Madilta", "Maeva", "Maisi", "Maisse", "Makko",
    "Malaika", "Malina", "Maliina", "Malka", "Malva", "Malvi", "Mandeliina", "Mandelina", "Mandolina", "Manja", "Mantu", "Manuele", "Manuella", "Mappela",
    "Marenka", "Mareta", "Marilii", "Marite", "Marjinga", "Marjuska", "Marka", "Marli", "Marlia", "Marna", "Mara", "Marsa", "Meela", "Meimei", "Meira",
    "Mekku", "Mele", "Meli", "Melodia", "Melva", "Meme", "Memma", "Memme", "Memmi", "Memmu", "Meni", "Meriella", "Merikeiju", "Merikki", "Merilii",
    "Merilla", "Merisa", "Merje", "Mertsa", "Meta", "Meteoora", "Metsäkeiju", "Metta", "Mianna", "Miija", "Miiju", "Miiru", "Miita", "Mikala", "Mikeli",
    "Mikla", "Miliana", "Militsa", "Miljaana", "Milli", "Milvi", "Mima", "Minki", "Minodora", "Miri", "Miritza", "Mirjaana", "Mirkitta", "Missu",
    "Misu", "Moon", "Mooni", "Muna", "Muru", "Muusa", "Mysi", "Myy", "Nanetta", "Nani", "Nanja", "Nanne", "Nao", "Narja", "Nastasia", "Nastassia",
    "Nata", "Natta", "Neariina", "Neelia", "Nenne", "Nerissa", "Nessa", "Nikka", "Ninetta", "Ninette", "Ninjana", "Ninne", "Nuria", "Nut", "Nuuni",
    "Oilikki", "Oivi", "Oivikki", "Okki", "Oktavia", "Oliva", "Olive", "Olvi", "Omena", "Oneida", "Onja", "Onna", "Onneli", "Orkkuli", "Otteljaana",
    "Ottelia", "Ottiliana", "Pamila", "Pato", "Patria", "Patrisia", "Paule", "Pelleriina", "Peninna", "Penina", "Penni", "Perla", "Pernella", "Petia",
    "Petriikka", "Petrika", "Petrina", "Petrissa", "Piija", "Piiku", "Piippa", "Piita", "Piiti", "Pijatta", "Pikka", "Pikke", "Pille", "Pinne",
    "Pippa", "Pirgitta", "Piri", "Pirja", "Pirjatta", "Pirke", "Pola", "Preeti", "Prikitta", "Priskilla", "Puolukka", "Pupu", "Päikki", "Queen",
    "Raia", "Raiku", "Railikki", "Ramina", "Ranita", "Ranjani", "Reetriika", "Renna", "Retriikka", "Ri", "Riida", "Rikissa", "Rilla", "Ripsa", "Ritja",
    "Roo", "Ru", "Ruu", "Safiira", "Sajatta", "Salle", "Samilla", "Sarala", "Saroja", "Sarolta", "Sarra", "Sarri", "Sateenkaari", "Satumarja", "Satusäde",
    "Saula", "Se", "Sea", "Seeli", "Seelia", "Seena", "Seeri", "Selima", "Sella", "Seni", "Senta", "Serafiima", "Seraina", "Sere", "Seri", "Serene",
    "Seriina", "Sesiilia", "Sesilja", "Si", "Siila", "Sikri", "Silina", "Silvana", "Sine", "Sinikukka", "Sinituuli", "Sinivuokko", "Sinne", "Sirina",
    "Sirka", "Sirki", "Sirkitta", "Siska", "Sistinja", "Skilla", "So", "Sohviia", "Sointi", "Sol", "Sola", "Staava", "Stefani", "Su", "Suleika",
    "Suliina", "Suna", "Sunita", "Sunna", "Sunneva", "Susanka", "Sussa", "Svanni", "Taikakukka", "Taikatuike", "Taikatuuli", "Taila", "Taineli",
    "Taisa", "Talvi", "Tamia", "Tamina", "Tamika", "Tassu", "Teela", "Teia", "Tella", "Teresita", "Tertta", "Tessi", "Tetta", "Tetti", "Ti", "Tiara",
    "Tii", "Tiija", "Tiila", "Tinna", "Tipi", "Tipsa", "Titania", "Titvi", "Tiuhti", "Tiuku", "Tomina", "Tonia", "Triina", "Tuiju", "Tuike", "Tuikku",
    "Tuila", "Tuiti", "Tulikukka", "Tulikki", "Tupuna", "Tutteli", "Tuua", "Tuuva", "Tuuve", "Ulpukka", "Ulrikke", "Ultriikka", "Una", "Une", "Undine",
    "Unni", "Ursule", "Usva", "Vaira", "Valla", "Ware", "Vasilista", "Veeruska", "Viipi", "Viira", "Viiu", "Viiva", "Viivu", "Viljakukka", "Viveke",
    "Xan", "Xena", "Zulu"];

    let randomNameFM = name5[Math.floor(Math.random() * name5.length)] + " " + name6[Math.floor(Math.random() * name6.length)];

    alert(randomNameFM);
}